import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Indie_Flower,
  Josefin_Sans,
} from "next/font/google";
import "./globals.css";
import Navabar from "./components/Navabar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const JosefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${JosefinSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="min-h-screen bg-background ">
          <div className="max-w-[850px] mx-auto px-4 sm:px-6 lg:px-8">
            <Navabar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
